name: Terraform CI/CD

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up AWS credentials
        env:
          AWS_CREDENTIALS: ${{ secrets.ONE }}
        run: |
          echo "$AWS_CREDENTIALS" | while IFS= read -r line; do
            echo "$line" >> $GITHUB_ENV
          done

      - name: Display Environment Variables
        run: |
          cat $GITHUB_ENV

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.0

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Install TFLint
        run: |
          curl -L "$(curl -s https://api.github.com/repos/terraform-linters/tflint/releases/latest | grep -o -E "https://.+?_linux_amd64.zip")" > tflint.zip && unzip tflint.zip && sudo mv tflint /usr/bin/
          tflint --version

      - name: Run TFLint
        run: tflint

      - name: Install Checkov
        run: |
          pip install checkov
          checkov --version

      - name: Run Checkov
        run: checkov -d .

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
